# T24 执行计划：全模块联调回归测试、缺陷闭环修复、输出后台操作手册

> **文件状态**：规划文档（待审核批准）
> **执行范围**：web_admin 全模块联调 + 缺陷修复 + docs 目录新增操作手册
> **禁止修改**：底层业务核心逻辑、README/DEVELOP_RULES/TASK_LIST 文档结构

---

## 1. 仓库调研结论

### 1.1 模块全景

```
web_admin/
├── main.py                      # 入口装配（auth/api/dashboard/data_center/compliance 路由）
├── auth.py                      # T18 权限体系（ROLE_SUPER_ADMIN / ROLE_OPS / ROLE_SALES / ROLE_COMPLIANCE）
├── menu.py                      # T18 菜单配置（已含 T19~T23 新增入口）
├── pages.py                     # T18~T23 页面渲染函数（40+ 路由）
├── api/
│   ├── dashboard.py             # T21 全链路看板数据接口
│   ├── data_center.py           # T21~T23 数据中心/批量/导出/异常/漏斗 核心 API（~50 端点）
│   ├── compliance_rules.py      # T20 合规审核规则
│   ├── accounts.py              # T18 账户管理
│   ├── channel_account.py       # 渠道账号绑定
│   ├── audit_log.py             # T18 审计日志
│   └── audit_enhanced.py        # T22 增强审计
├── templates/                   # 页面模板（如有）
└── static/
    ├── js/admin.js              # T18~T23 交互逻辑（4000+ 行 JS，全页面入口）
    └── css/admin.css            # T18~T23 样式（300+ 行样式）

docs/                            # 计划新建操作手册存放位置
tests/                           # pytest 回归用例集（当前 221 条）
```

### 1.2 测试覆盖现状

| 维度 | 现状 | 建议 |
|------|------|------|
| 单元测试（pytest） | 221 条，覆盖模型、权限、API、页面基础 | 保持稳定，不降低 |
| 端到端手工测试 | 未系统性执行 | T24 专项补全 |
| 权限边界测试 | 未覆盖所有 4 角色 × 40 页面的组合 | T24 专项巡检 |
| 脱敏检查 | 未全页面巡检 | T24 专项巡检 |
| 操作日志留痕 | 未逐条验证 | T24 专项验证 |
| 大数据量压力 | 未验证 | T24 轻量基准测试 |

### 1.3 已知风险项

1. **`admin.js` 4000+ 行全量单文件**：存在重复代码、部分 JS 函数与新路由不一致的潜在问题
2. **`data_center.py` 50+ API 端点**：权限注解覆盖率需逐一确认
3. **脱敏实现依赖 `_mask` 前端渲染辅助**：部分旧页面可能遗漏脱敏标记
4. **Redis 可选依赖**：异常/漏斗/批量在 Redis 不可用时走模拟数据链路，需验证交互鲁棒性
5. **操作日志写入链路分散**：部分操作入口可能未接入 audit_log 系统

---

## 2. 分步执行流程（5 阶段 × 21 子任务）

```
Phase A：测试环境与用例准备
Phase B：端到端全链路手工测试
Phase C：权限、合规、边界专项测试
Phase D：缺陷闭环修复
Phase E：操作手册输出 + 全量回归验证
```

### Phase A：测试环境与用例准备（3 子任务）

#### A1 静态代码巡检 — 权限注解一致性验证

**目标**：确保所有操作类 API（POST/PUT/DELETE）与敏感页面均挂接 `Depends(require_admin)` 且使用正确角色权限。

**步骤**：
1. 枚举 `web_admin/api/*.py` 下所有路由定义（`@router.get/post/put/delete`）
2. 对每个路由检查：
   - 是否已挂接 `Depends(require_admin)` 或 `Depends(get_current_admin)`
   - POST/PUT/DELETE 类路由是否使用 `require_admin`（拒绝 `get_current_admin` 弱校验）
   - 敏感数据路由是否要求 `btn.data_center.view_raw` 或 `btn.data_center.export_plain`
3. 枚举 `web_admin/pages.py` 所有 HTMLResponse 路由，检查：
   - 是否通过 `_render_with_permission` 校验
   - 权限 key 是否与 menu.py 的角色配置一致
4. 输出《权限注解差异清单》（CSV）：路由、当前注解、期望注解、问题等级

**交付**：`docs/T24_security_audit.csv`（计划中产物）

#### A2 脱敏点全覆盖巡检

**目标**：确认所有含隐私字段的页面/接口均通过 `_mask` 或后端 `mask_phone()` 进行脱敏。

**步骤**：
1. `web_admin/api/data_center.py` 中全文搜索 "phone"、"email"、"mobile"、"contact"、"wechat"、"qq"、"联系方式"，确认返回字段前均经过 `mask_phone()`
2. `web_admin/static/js/admin.js` 中搜索上述关键字，确认渲染时调用 `admin.maskCell` 或 `mask` 辅助函数
3. `web_admin/pages.py` 搜索上述关键字，确认模板文本已声明脱敏
4. 检查明文查看入口：所有「查看明文」按钮必须挂接 `btn.data_center.view_raw` 权限，且点击动作写入 audit_log
5. 检查导出接口：`/data_center/export/submit` 默认参数 `is_plain=False`，明文需检查 `btn.data_center.export_plain`

**交付**：`docs/T24_mask_audit.csv`

#### A3 测试数据准备 — 预置最小全链路数据集

**目标**：提供一批预置数据，使得端到端测试时各阶段均有数据可操作，无需实时依赖外部采集。

**步骤**：
1. 在 `data_center.py` 的模拟数据生成函数中，补充 7 渠道 × 3 样本数据（共 21 条）：
   - 含完整字段：渠道名、采集时间、企业名称、联系方式、需求、标签、当前阶段
   - 覆盖"正常流转"、"异常卡住"、"合规争议"三种状态
2. 确保模拟数据在 Redis 可用/不可用两种场景下均能渲染
3. 不新增新路由，不修改真实底层数据库结构；仅补充 `_simulate_*` 辅助函数

### Phase B：端到端全链路手工测试（7 子任务）

#### B1~B7 7 大渠道独立走通全链路

```
测试链路（每条链路 10 步，总计 70 用例）：
① 创建采集任务（分渠道差异化表单）
    → 检查：表单字段完整性、必填校验、合规协议勾选
② 提交合规审核（若渠道要求审批）
    → 检查：审批队列可见、可驳回/通过、状态同步
③ 启动采集（手动启动，模拟数据返回）
    → 检查：任务状态流转、日志输出、原始数据生成
④ 手动触发清洗流水线
    → 检查：原始 → 结构化字段映射、企业名/联系方式识别
⑤ 商机分级（评分+行业标签）
    → 检查：打分数值合理性、标签可编辑、分级状态更新
⑥ 手动发起触达（短信/邮件/企微）
    → 检查：消息提交、发送状态、失败重试
⑦ 分配销售人员
    → 检查：下拉列表人员、分配后销售可见性、审计记录
⑧ 录入跟进记录
    → 检查：时间线渲染、跟进内容可检索
⑨ 手动关闭商机（成交/流失/无效）
    → 检查：最终状态写入、漏斗统计更新
⑩ 数据导出 + 操作日志对账
    → 检查：导出数据字段、脱敏状态、日志条目匹配
```

**渠道清单**：
1. 企业信息黄页
2. 行业垂直门户
3. LinkedIn 商务平台
4. 短视频平台
5. 小红书社区
6. 供需平台/B2B
7. 招投标/采购公告

**每渠道用例记录字段**：测试日期、测试员、渠道、步骤编号、预期结果、实际结果、是否通过、缺陷编号（如失败）

**交付**：`docs/T24_e2e_test_report.md`

### Phase C：权限、合规、边界专项测试（4 子任务）

#### C1 四级角色权限矩阵验证

**测试方法**：
1. 使用 `super_admin / ops / sales / compliance` 各登录一次
2. 逐一访问所有 `/admin/…` 页面路由（约 40 个）
3. 逐一调用所有 `/api/admin/…` POST/PUT/DELETE 接口（约 30 个）
4. 预期行为：超出角色权限的 → 403/重定向到登录；正常权限 → 200 正常响应

**特别检查**：
- `compliance` 角色不应能修改商机评分、发起触达
- `sales` 角色不应能启动采集任务、调整合规规则
- `ops` 角色不应能查看明文数据、分配超管权限
- 所有角色均不能访问其他角色专属页面（即使知道 URL）

#### C2 隐私字段脱敏专项

**测试方法**：
1. 逐页面截屏或浏览器开发者工具检查 HTML/JSON 响应
2. 搜索正则 `1[3-9]\d{9}`（手机号）、`[\w.+-]+@[\w-]+\.[\w.-]+`（邮箱）
3. 验证：搜索命中必须是 `****` 或 `1xx****xx` 格式（脱敏后）
4. 明文查看功能：仅 super_admin 可切换，切换后触发审计日志

#### C3 操作日志留痕专项

**测试方法**：
1. 执行 B 链路时，每完成一次 POST/PUT/DELETE 操作
2. 立即访问 `/admin/audit_log`（或对应审计查询接口）
3. 验证：操作人、时间、操作类型、对象 ID、前后内容（如适用）均完整
4. 检查审计日志自身不可修改、不可删除

**不可修改验证**：尝试直接调用 audit 相关 PUT/DELETE → 预期 404/403

#### C4 边界与异常场景

**测试点清单**（25+ 条）：

| 场景 | 测试输入 | 预期结果 |
|------|---------|---------|
| 大数据列表 | 列表分页 → 第 1/10/100/500 页 | 响应 < 3s，不崩溃 |
| 空列表 | 无数据返回 | 显示空状态，不报错 |
| 非法 ID | `lead_id=99999999` / `task_id=abc` | 404 + 友好提示 |
| 越权操作 | sales 角色触发合规规则修改 | 403 + 审计记录 |
| 批量空输入 | 批量操作 item_ids 留空 | 前端校验拦截 + 友好提示 |
| 批量超限 | item_ids=10000 条 | 截断或返回错误，不服务超时 |
| 导出超限 | 请求导出 10 万行 | 异步任务 + 进度条，不阻塞 |
| Redis 不可用 | 禁用 Redis 连接 | 走模拟链路，页面仍能渲染 |
| 网络异常 | 前端发起 fetch 时断网 | 前端提示 "请求失败，请重试"，不崩溃 |
| 表单重复提交 | 快速双击"创建任务"按钮 | 仅创建 1 条，防重复提交 |

**交付**：`docs/T24_boundary_test_report.md`

### Phase D：缺陷闭环修复（4 子任务）

#### D1 缺陷管理流程

```
发现缺陷 → 登记（缺陷编号 T24-BUG-xxx） → 分类（P0 阻断 / P1 严重 / P2 一般 / P3 提示）
   ↓
分析根因 → 评估影响范围 → 制定修复方案（仅 bug 修复 + 交互优化，不改架构）
   ↓
代码修复 → 同步更新测试用例 → 本地通过 pytest
   ↓
回归验证 → 执行原失败用例，确认通过，且无其他用例回退
   ↓
关闭缺陷 → 更新缺陷清单状态
```

**缺陷登记字段**：编号、发现人、发现日期、所属模块、严重级别、复现步骤、预期结果、实际结果、修复人、修复日期、回归结果

**交付**：`docs/T24_bug_tracker.md`（缺陷清单 + 状态流转表）

#### D2 修复原则与限制

1. **修复范围**：仅 web_admin 层（`auth.py`、`menu.py`、`pages.py`、`api/*.py`、`static/js/admin.js`、`static/css/admin.css`）
2. **不新增功能**：修复仅针对测试中发现的 bug 与交互体验问题
3. **不改底层**：禁止修改 `biz_core/*`、`data_layer/*` 等底层业务模块
4. **零回归承诺**：每修复一次，必须执行完整 pytest 套件，确认 221+ 用例仍全部通过
5. **修复后需补充测试用例**：对每个 P0/P1 缺陷，在 `tests/` 下补充对应的单元测试

#### D3 典型缺陷场景预判与修复方案模板

| 可能缺陷 | 修复思路 | 涉及文件 |
|----------|---------|---------|
| 某页面未挂权限校验 | 补充 `_render_with_permission` 装饰器 | pages.py |
| API 缺失 `require_admin` | 路由参数补充 `Depends(require_admin)` | api/data_center.py |
| 联系方式明文泄露 | 在 `data_center.py` 对应字段返回前套 `mask_phone()`，或前端 JS 中调用 `admin.maskCell` | data_center.py + admin.js |
| 批量操作空输入提交成功 | 在 JS 中提交前校验 `items.length > 0`，服务端同步校验 | admin.js + data_center.py |
| 审计日志缺失某操作 | 在操作完成后追加 `_record_audit()` 调用 | api/*.py |
| 页面无数据时布局错乱 | CSS 中添加 `.empty-state` 样式，或 JS 中做长度判断 | admin.js + admin.css |
| Redis 不可用时页面崩溃 | 在 `_get_redis()` 调用外包 try/except，回退到模拟数据 | data_center.py |

#### D4 修复优先级定义

- **P0（阻断级）**：权限越权、隐私泄露、页面崩溃 — 必须立即修复
- **P1（严重级）**：功能不可用、数据流转中断 — 本轮必修复
- **P2（一般级）**：交互体验差、布局错位、文案错误 — 本轮尽量修复
- **P3（提示级）**：非关键文案、低概率异常 — 记录待后续优化

### Phase E：操作手册输出 + 全量回归（3 子任务）

#### E1 操作手册编写

**输出位置**：`docs/WEB_ADMIN_OPERATION_MANUAL.md`

**目录结构**：

```
# Web 管理后台操作手册

## 1. 系统概述
## 1.1 系统架构与角色体系
## 1.2 登录与登出
## 1.3 页面导航说明

## 2. 角色权限速查表
## 2.1 super_admin（超级管理员）权限矩阵
## 2.2 ops（运营）权限矩阵
## 2.3 sales（销售）权限矩阵
## 2.4 compliance（合规）权限矩阵

## 3. 运营操作手册（ops 角色）
## 3.1 采集任务管理
##   3.1.1 创建采集任务（7 渠道差异化表单）
##   3.1.2 任务启停与重试
##   3.1.3 批量操作中心使用
## 3.2 全链路看板与数据监控
## 3.3 异常数据池处理
## 3.4 分渠道转化效果分析
## 3.5 数据导出与下载

## 4. 销售操作手册（sales 角色）
## 4.1 商机看板与跟进
## 4.2 商机分级与调级
## 4.3 手动发起触达
## 4.4 录入跟进记录
## 4.5 关闭商机（成交/流失/无效）

## 5. 合规操作手册（compliance 角色）
## 5.1 采集任务合规审核
## 5.2 审核规则配置
## 5.3 违规数据复核与处理
## 5.4 合规审计日志查看

## 6. 管理员操作手册（super_admin 角色）
## 6.1 账号与角色管理
## 6.2 权限配置与查看
## 6.3 渠道规则与账号绑定
## 6.4 全量审计日志
## 6.5 系统健康检查

## 7. 数据中心（全角色共享视图）
## 7.1 全链路 6 阶段看板
## 7.2 分阶段明细列表筛选与排序
## 7.3 商机全生命周期时间线追踪
## 7.4 异常数据池操作指南
## 7.5 分渠道转化漏斗看板解读
## 7.6 批量操作中心使用规范
## 7.7 数据导出中心使用规范

## 8. 操作规范与合规要求
## 8.1 数据使用承诺
## 8.2 隐私字段查看规范
## 8.3 批量操作风险提示
## 8.4 审计日志不可删除说明

## 9. 常见问题 FAQ
## 9.1 登录与权限类
## 9.2 数据查询与展示类
## 9.3 异常处理类
## 9.4 批量操作类
## 9.5 导出与下载类

## 10. 附录
## 10.1 页面路由速查表
## 10.2 权限 key 速查表
## 10.3 脱敏规则说明
## 10.4 操作日志字段说明
```

**编写原则**：
1. 每个操作步骤配套"操作路径 → 截图位置 → 预期结果 → 注意事项"四要素
2. 每角色章节独立完整，可单独阅读
3. 与实际功能精确对应，禁止在手册中描述测试中发现不工作的功能
4. 更新代码后若改变操作流程，手册须同步修订

#### E2 配套截图与视觉指引

**截图清单**（每角色 8~12 张，合计约 40 张）：
- 登录页、首页 Dashboard
- 各阶段明细页（采集/清洗/合规/分级/触达/闭环）
- 商机时间线详情页
- 异常数据池页 + 批量操作弹窗
- 分渠道漏斗看板
- 批量操作中心（任务提交 + 进度查询）
- 数据导出中心（表单 + 下载）
- 合规审核工作台
- 权限 denied 页面

**命名规范**：`docs/screenshots/[role]_[page]_[step].png`

#### E3 最终全量回归验证

**执行顺序**：
1. `python -m pytest tests/ -v` → 221+ 全量单元测试通过
2. 全链路 7 渠道手工回归（B1~B7） → 全链路 70/70 通过
3. 权限专项 C1 → 无越权漏洞
4. 脱敏专项 C2 → 无明文泄露
5. 留痕专项 C3 → 操作全记录
6. 边界专项 C4 → 25+ 边界场景通过

**交付**：`docs/T24_final_regression_report.md`

---

## 3. 文件与模块修改清单

### 3.1 允许修改文件

| 文件 | 预期变更类型 | 说明 |
|------|-------------|------|
| `web_admin/auth.py` | 权限注解修正（P0/P1 缺陷） | 仅补遗漏的角色校验，不改变权限语义 |
| `web_admin/menu.py` | 菜单文案一致性调整 | 不改新增逻辑 |
| `web_admin/pages.py` | 页面错误文案/路由修复、脱敏补充 | 不新增页面路由 |
| `web_admin/api/data_center.py` | API 权限校验补全、脱敏调用补全、交互优化 | 不新增独立业务功能 |
| `web_admin/api/*.py`（其他 API 文件） | 审计日志调用补全、输入校验强化 | 同上 |
| `web_admin/static/js/admin.js` | JS 交互修复、防重复提交、错误提示优化 | 不改页面结构框架 |
| `web_admin/static/css/admin.css` | 空状态样式、响应式布局微调 | 不改基础主题 |

### 3.2 新增文件（docs 目录）

| 文件 | 说明 |
|------|------|
| `docs/WEB_ADMIN_OPERATION_MANUAL.md` | 操作手册主文档（核心交付） |
| `docs/T24_e2e_test_report.md` | 端到端测试报告 |
| `docs/T24_boundary_test_report.md` | 边界异常测试报告 |
| `docs/T24_bug_tracker.md` | 缺陷清单与闭环记录 |
| `docs/T24_final_regression_report.md` | 最终全量回归报告 |
| `docs/T24_security_audit.csv` | 权限注解差异清单（测试产物） |
| `docs/T24_mask_audit.csv` | 脱敏点差异清单（测试产物） |
| `docs/screenshots/*.png` | 操作手册配套截图 |

### 3.3 禁止修改文件

```
README.md                 （可补充 doc 链接，不改项目结构章节）
DEVELOP_RULES.md          （严格遵循，不修改）
docs/TASK_LIST.md         （严格遵循，不修改）
biz_core/* / data_layer/*  （底层业务核心，不动）
外部爬虫调度服务配置       （不动）
```

---

## 4. 潜在依赖与注意事项

### 4.1 测试环境依赖

```
必需：
- Python 3.11+
- FastAPI + Uvicorn（或对应 WSGI 启动器）
- pytest + httpx（已在 tests/ 中使用）
- 浏览器（Chrome/Edge，用于手工测试 + 截图）

可选：
- Redis（启用真实状态存储，不启用则走模拟）
- 真实渠道账号（用于真实数据采集，若无则走模拟链路）
```

### 4.2 注意事项清单

1. **浏览器兼容性**：T24 测试默认使用最新版 Chrome，不做 IE11/低版本浏览器验证
2. **数据清理**：测试数据使用模拟生成，不对真实底层数据库写入（除非在隔离测试库）
3. **操作日志污染**：测试期间会产生大量 audit_log，需在测试结束后明确标记为"测试数据"
4. **Redis 双场景**：必须在 Redis 可用和不可用两种场景下各跑一次关键链路
5. **明文查看授权**：测试脱敏时，super_admin 查看明文需在审计日志中留痕，需测试人员在审计页核实
6. **截图时机**：截图应在正常操作流程中抓取，避免包含测试者个人信息
7. **并发测试**：批量/导出能力需同时触发多个任务，验证异步执行的并发稳定性

### 4.3 风险与缓解策略

| 风险 | 影响 | 缓解策略 |
|------|------|---------|
| 发现 P0 级别越权漏洞 | 高：需紧急修复 | 在 Phase C1 中优先执行，发现即停其他工作，修复后再继续 |
| 脱敏缺失导致明文泄露 | 高：合规风险 | Phase A2 全量巡检，发现缺失立即在 data_center.py/JS 中补充 mask 调用 |
| 交互缺陷数量远超预期 | 中：延误交付 | 缺陷分级，P3 留记录延后处理，P0/P1 必修 |
| pytest 基线回归 | 中：引入新 bug | Phase D 中每次修复后立即跑全量 pytest，确保未引入回归 |
| docs 目录不存在 | 低：文件路径问题 | Phase E1 前自动创建目录（mkdir -p docs/screenshots） |

---

## 5. 测试用例汇总

### 5.1 自动化用例

```
现有：tests/ 目录下 221 条 pytest 用例
补充：每发现 1 个 P0/P1 缺陷，对应补充 1 条测试用例
目标最终：≥ 225 条（视缺陷数量而定）
```

### 5.2 手工用例

| 类型 | 条数 | 执行方式 |
|------|------|---------|
| 端到端全链路 | 7 渠道 × 10 步 = 70 | 手工 |
| 权限矩阵验证 | 4 角色 × 40 路由 + 30 接口 ≈ 280 | 手工 + curl |
| 脱敏专项 | 全页面巡检 ≈ 40 | 手工 + 浏览器搜索 |
| 操作日志留痕 | 全操作类入口 ≈ 50 | 手工 + 审计页对比 |
| 边界异常场景 | 25+ | 手工 |
| **合计** | **≈ 465 条手工用例** | |

---

## 6. 分步执行时间线（逻辑顺序）

```
第 1 步：Phase A 测试准备（A1~A3）
   产出：权限巡检清单、脱敏点清单、预置测试数据

第 2 步：Phase B 端到端测试（B1~B7）
   产出：7 渠道全链路测试报告、缺陷初步清单

第 3 步：Phase C 专项测试（C1~C4）
   产出：权限/脱敏/留痕/边界 4 份专项报告、完整缺陷清单

第 4 步：Phase D 缺陷闭环修复（D1~D4）
   产出：缺陷修复记录、补充测试用例、pytest 全绿
   ↓ 修复后重跑 B/C 中失败用例 → 全用例通过

第 5 步：Phase E 操作手册 + 最终回归（E1~E3）
   产出：WEB_ADMIN_OPERATION_MANUAL.md + 截图 + 最终回归报告
```

---

## 7. 验收标准

1. ✅ pytest 自动化用例 ≥ 221 条，100% 通过
2. ✅ 7 大渠道端到端链路 70/70 全走通
3. ✅ 权限矩阵无越权漏洞（280 个组合检查）
4. ✅ 隐私字段全页面/全接口脱敏，无明文泄露
5. ✅ 所有操作类 API/PUT/DELETE 均有审计记录
6. ✅ 25+ 边界异常场景处理正常，无崩溃
7. ✅ `docs/WEB_ADMIN_OPERATION_MANUAL.md` 完整输出，含 40 张截图
8. ✅ 缺陷清单中 P0/P1 全部关闭，P2 关闭率 ≥ 80%
9. ✅ `README.md`、`DEVELOP_RULES.md`、`docs/TASK_LIST.md` 结构未改动
10. ✅ 最终提交信息格式：

```
feat(T24): 完成全模块联调回归测试、缺陷闭环修复、输出操作手册
- 全链路端到端手工测试：7 渠道×10 步，覆盖数据流转/状态同步/日志留痕
- 权限合规专项：4 角色权限矩阵+脱敏全页面巡检，无明文泄露与越权
- 边界异常场景：25+ 场景验证，鲁棒性提升
- 缺陷闭环：P0/P1 缺陷全部修复，pytest 221+ 全量通过
- 输出《Web 管理后台操作手册》docs/WEB_ADMIN_OPERATION_MANUAL.md（40+ 截图）
- 严格遵循 DEVELOP_RULES.md，仅 bug 修正与交互优化，不改动底层业务逻辑
```

---

## 8. 变更范围摘要

```
修改文件数：~6-8 个（web_admin 下）
新增文件数：~8 个（docs/ 下）
  - WEB_ADMIN_OPERATION_MANUAL.md
  - T24_e2e_test_report.md
  - T24_boundary_test_report.md
  - T24_bug_tracker.md
  - T24_final_regression_report.md
  - T24_security_audit.csv
  - T24_mask_audit.csv
  - screenshots/*.png（~40 张）
代码增量：取决于缺陷数量（预估 500~2000 行）
文档增量：预估 30~50 页 Markdown
测试用例增量：pytest 预计 +4~10 条
```
